/* photoshrink.net service worker. GENERATED by tools/build_sw.py, do not edit.
   Run `python3 tools/build_sw.py` after any page, stylesheet or app.js change.
   VERSION is a hash of every precached file, so the cache name changes on
   each deploy that changes the offline set. */

const VERSION = "17bace71f373";
const CACHE = "photoshrink-" + VERSION;
const PRECACHE = [
  "/",
  "/resize-image.html",
  "/compress-image.html",
  "/crop-image.html",
  "/convert-image.html",
  "/rotate-image.html",
  "/image-to-base64.html",
  "/favicon-generator.html",
  "/redact-screenshot.html",
  "/blur-image.html",
  "/exif-viewer.html",
  "/compress-image-to-100kb.html",
  "/compress-image-to-200kb.html",
  "/compress-image-to-500kb.html",
  "/compress-image-to-1mb.html",
  "/compress-image-for-email.html",
  "/compress-image-for-discord.html",
  "/instagram-post-size.html",
  "/instagram-story-size.html",
  "/instagram-reel-size.html",
  "/instagram-profile-picture-size.html",
  "/youtube-thumbnail-size.html",
  "/youtube-banner-size.html",
  "/twitter-header-size.html",
  "/twitter-post-image-size.html",
  "/facebook-cover-photo-size.html",
  "/facebook-post-image-size.html",
  "/linkedin-banner-size.html",
  "/linkedin-post-image-size.html",
  "/tiktok-video-size.html",
  "/pinterest-pin-size.html",
  "/discord-banner-size.html",
  "/discord-server-icon-size.html",
  "/twitch-offline-banner-size.html",
  "/twitch-profile-banner-size.html",
  "/zoom-virtual-background-size.html",
  "/spotify-playlist-cover-size.html",
  "/png-to-jpg.html",
  "/jpg-to-png.html",
  "/webp-to-jpg.html",
  "/webp-to-png.html",
  "/png-to-webp.html",
  "/jpg-to-webp.html",
  "/jpeg-to-png.html",
  "/assets/css/styles.css",
  "/assets/js/app.js"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // {cache: "reload"} bypasses the HTTP cache, so a stale copy of a page
      // can not feed old bytes into a new cache name.
      cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "reload" })))
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith("photoshrink-") && key !== CACHE)
          .map((key) => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});

// Cache keys the worker tries for one navigation, in order. The site keeps
// `/x.html` in the cache and serves it for `/x`, `/x/` and `/x/index.html`.
function navigationKeys(pathname) {
  const keys = [pathname];
  if (pathname.endsWith("/")) {
    keys.push(pathname + "index.html");
    if (pathname !== "/") keys.push(pathname.slice(0, -1) + ".html");
  } else if (pathname.endsWith("/index.html")) {
    keys.push(pathname.slice(0, -"index.html".length));
    keys.push(pathname.slice(0, -"/index.html".length) + ".html");
  } else if (!/\.[a-z0-9]+$/i.test(pathname)) {
    keys.push(pathname + ".html");
    keys.push(pathname + "/");
  }
  return keys;
}

async function fromCache(request) {
  const hit = await caches.match(request, { ignoreSearch: false });
  if (hit || request.mode !== "navigate") return hit;
  const url = new URL(request.url);
  for (const key of navigationKeys(url.pathname)) {
    const page = await caches.match(key);
    if (page) return page;
  }
  return undefined;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  // The worker handles same-origin GET requests only. Every other request,
  // the AdSense script and every other third-party URL included, goes
  // straight to the network. The worker never intercepts it and never
  // caches it.
  if (request.method !== "GET") return;
  if (new URL(request.url).origin !== self.location.origin) return;

  // Cache first. The precache is the whole offline set, so a network
  // response is never written into the cache at runtime.
  event.respondWith(
    fromCache(request).then((hit) => hit || fetch(request))
  );
});
