#!/usr/bin/env python3
"""Minify assets/js/app.js into assets/js/app.min.js.

`assets/js/app.js` is the source. It is readable, commented and covered by
`tools/app.test.js`. It is 133 KB, and it loads on all 88 pages, so the source
is not what a visitor should download.

    python3 tools/build_app.py          # write assets/js/app.min.js
    python3 tools/build_app.py --check  # exit 1 if the minified file is stale

The minifier is terser. The script uses a terser on PATH if there is one, and
falls back to `npx --yes terser@5`, which needs a network connection the first
time. Nothing else in this repo needs a toolchain, and nothing at run time
needs one: `app.min.js` is committed, so a deploy is still a plain file copy.

Settings, and why:

    compress   on, default passes
    mangle     on, top-level names NOT mangled

`assets/js/app.js` ends with a `typeof module !== "undefined"` block that
exports the pure helpers for the Node test. Top-level mangling would rename
those helpers and the export object would carry the wrong keys, so it stays
off. The saving from top-level mangling is small and the failure is silent.

Run this after every edit to `assets/js/app.js`, then run
`python3 tools/build_sw.py`, because the worker hashes what it precaches.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets/js/app.js"
OUT = ROOT / "assets/js/app.min.js"

BANNER = "/* photoshrink.net — generated by tools/build_app.py from assets/js/app.js. */"

TERSER_ARGS = [
    "--compress",
    "--mangle",
    "--format", "comments=false",
]


def terser_command():
    """The terser to run: one on PATH, else npx."""
    found = shutil.which("terser")
    if found:
        return [found]
    npx = shutil.which("npx")
    if not npx:
        raise SystemExit("no terser and no npx on PATH — install terser to build app.min.js")
    return [npx, "--yes", "terser@5"]


def minify():
    cmd = terser_command() + [str(SRC)] + TERSER_ARGS
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit("terser failed:\n" + result.stderr.strip())
    body = result.stdout.strip()
    if not body:
        raise SystemExit("terser produced nothing")
    return BANNER + "\n" + body + "\n"


def main():
    ap = argparse.ArgumentParser(description="Minify app.js.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if assets/js/app.min.js does not match app.js")
    args = ap.parse_args()

    text = minify()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    saved = 100 - round(len(text) / len(SRC.read_text(encoding="utf-8")) * 100)
    if args.check:
        if text != current:
            print("assets/js/app.min.js is stale: run python3 tools/build_app.py")
            return 1
        print("assets/js/app.min.js is current (%d bytes, %d%% off the source)"
              % (len(text), saved))
        return 0
    OUT.write_text(text, encoding="utf-8")
    print("wrote assets/js/app.min.js (%d bytes, %d%% off the source)"
          % (len(text), saved))
    return 0


if __name__ == "__main__":
    sys.exit(main())
