#!/usr/bin/env python3
"""Write sw.js, the service worker that makes the "works offline" claim true.

    python3 tools/build_sw.py           # rewrite sw.js
    python3 tools/build_sw.py --check   # exit 1 if sw.js is stale

Stdlib only, no build step at deploy time. Run it last, after
build_size_pages.py, build_convert_pages.py and sync_nav.py, because the cache
name is a hash of the page bytes that those scripts write.

The precache list is not typed by hand. It comes from two places:

- sitemap.xml, for every tool page and the homepage. Pages under /articles/
  and the two legal pages are content, not tools, so the list skips them.
- nav_data.CONVERT_ALIASES, for the alias pages that carry rel=canonical and
  are kept out of the sitemap on purpose.

Each sitemap URL maps to the file the server serves for it. GitHub Pages
serves `<slug>.html` for `/<slug>`, so the list holds `/<slug>.html`. The
homepage is `/`. The list also holds every same-origin stylesheet and script
that those pages reference.

The cache name is "photoshrink-" plus the first 12 hex characters of a SHA-256
over the content of every precached file. A change to any page, the stylesheet
or app.js gives a new name, so the worker replaces the old cache on the next
visit. The name never changes when nothing in the offline set changed.
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import nav_data as D  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://photoshrink.net"
PREFIX = "photoshrink"
OUT = ROOT / "sw.js"

# Sitemap entries that are content, not tools. They stay online-only.
SKIP_PREFIXES = ("/articles/",)
SKIP_PATHS = {"/privacy.html", "/terms.html"}


def sitemap_paths():
    """Every <loc> in sitemap.xml as a site-relative path, in file order."""
    text = (ROOT / "sitemap.xml").read_text(encoding="utf-8")
    out = []
    for loc in re.findall(r"<loc>\s*([^<\s]+)\s*</loc>", text):
        if not loc.startswith(SITE):
            raise SystemExit("sitemap entry is not on %s: %s" % (SITE, loc))
        path = loc[len(SITE):] or "/"
        if path.startswith(SKIP_PREFIXES) or path in SKIP_PATHS:
            continue
        out.append(path)
    return out


def page_file(path):
    """The repo file that the server sends for a sitemap path."""
    if path == "/":
        return ROOT / "index.html"
    if path.endswith(".html"):
        return ROOT / path.lstrip("/")
    return ROOT / (path.strip("/") + ".html")


def asset_urls(html):
    """Same-origin stylesheet and script URLs that one page references.

    A `?v=` query, if a page ever carries one, stays exactly as written so the
    cache key equals the request URL.
    """
    urls = []
    for tag in re.findall(r"<(?:link|script)\b[^>]*>", html):
        if tag.startswith("<link") and 'rel="stylesheet"' not in tag:
            continue
        attr = "href" if tag.startswith("<link") else "src"
        found = re.search(r'\b%s="([^"]+)"' % attr, tag)
        if not found:
            continue
        url = found.group(1)
        # Only a root-relative path is same-origin for certain. A full URL is
        # a third party, and the worker must never precache one of those.
        if not url.startswith("/") or url.startswith("//"):
            continue
        urls.append(url)
    return urls


def precache():
    """(url, file) pairs, pages first, then their assets, no duplicates."""
    pages = sitemap_paths()
    pages += ["/%s.html" % a["slug"] for a in D.CONVERT_ALIASES]
    entries = []
    seen = set()

    def add(url, file):
        if url in seen:
            return
        if not file.is_file():
            raise SystemExit("precache entry %s has no file at %s" % (url, file))
        seen.add(url)
        entries.append((url, file))

    assets = []
    for path in pages:
        file = page_file(path)
        url = path if path == "/" else "/" + file.relative_to(ROOT).as_posix()
        add(url, file)
        for asset in asset_urls(file.read_text(encoding="utf-8")):
            if asset not in assets:
                assets.append(asset)
    for url in assets:
        add(url, ROOT / url.split("?", 1)[0].lstrip("/"))
    return entries


def version(entries):
    digest = hashlib.sha256()
    for url, file in entries:
        digest.update(url.encode("utf-8"))
        digest.update(b"\0")
        digest.update(file.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()[:12]


TEMPLATE = """\
/* photoshrink.net service worker. GENERATED by tools/build_sw.py, do not edit.
   Run `python3 tools/build_sw.py` after any page, stylesheet or app.js change.
   VERSION is a hash of every precached file, so the cache name changes on
   each deploy that changes the offline set. */

const VERSION = "%(version)s";
const CACHE = "%(prefix)s-" + VERSION;
const PRECACHE = [
%(precache)s
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // {cache: "reload"} bypasses the HTTP cache, so a stale copy of a page
      // can not feed old bytes into a new cache name.
      cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "reload" })))
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith("%(prefix)s-") && key !== CACHE)
          .map((key) => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});

// Cache keys the worker tries for one navigation, in order. The site keeps
// `/x.html` in the cache and serves it for `/x`, `/x/` and `/x/index.html`.
function navigationKeys(pathname) {
  const keys = [pathname];
  if (pathname.endsWith("/")) {
    keys.push(pathname + "index.html");
    if (pathname !== "/") keys.push(pathname.slice(0, -1) + ".html");
  } else if (pathname.endsWith("/index.html")) {
    keys.push(pathname.slice(0, -"index.html".length));
    keys.push(pathname.slice(0, -"/index.html".length) + ".html");
  } else if (!/\\.[a-z0-9]+$/i.test(pathname)) {
    keys.push(pathname + ".html");
    keys.push(pathname + "/");
  }
  return keys;
}

async function fromCache(request) {
  const hit = await caches.match(request, { ignoreSearch: false });
  if (hit || request.mode !== "navigate") return hit;
  const url = new URL(request.url);
  for (const key of navigationKeys(url.pathname)) {
    const page = await caches.match(key);
    if (page) return page;
  }
  return undefined;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  // The worker handles same-origin GET requests only. Every other request,
  // the AdSense script and every other third-party URL included, goes
  // straight to the network. The worker never intercepts it and never
  // caches it.
  if (request.method !== "GET") return;
  if (new URL(request.url).origin !== self.location.origin) return;

  // Cache first. The precache is the whole offline set, so a network
  // response is never written into the cache at runtime.
  event.respondWith(
    fromCache(request).then((hit) => hit || fetch(request))
  );
});
"""


def render(entries):
    rows = ",\n".join("  %s" % js_string(url) for url, _ in entries)
    return TEMPLATE % {"version": version(entries), "prefix": PREFIX, "precache": rows}


def js_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser(description="Write sw.js.")
    ap.add_argument("--check", action="store_true", help="exit 1 if sw.js is stale")
    args = ap.parse_args()

    entries = precache()
    content = render(entries)
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None

    if args.check:
        if current != content:
            print("sw.js is stale, run: python3 tools/build_sw.py")
            return 1
        print("sw.js is current (%d precache entries)" % len(entries))
        return 0

    if current == content:
        print("sw.js is current (%d precache entries)" % len(entries))
        return 0
    OUT.write_text(content, encoding="utf-8")
    print("wrote sw.js (%d precache entries, cache %s-%s)"
          % (len(entries), PREFIX, version(entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
